### PR TITLE
Update readme, add error detail to exception in send

### PR DESCRIPTION
**Pull request by lindsaymarkward**
Hi Bill. 
Jim and I would like to move the Home Assistant platform for MythTV forward to make it a standard included platform, which requires the services API to be installable from PyPI.
I know we talked about this in the past and you didn't want to maintain it, but I'm happy to do this... if that's OK with you.
So:
1. Are you happy for me to upload the package to PyPI?
2. Is there anything I should know (changes that should/will be made, or anything) before I do this?
3. How would updates in the future work? I'm happy to just copy them over from the official codebase if I know what you want.

Thanks!

### CODE REVIEW

**Comment by lindsaymarkward** [comment]
@calmor15014 - I've taken this step mostly just to contact Bill and find out about publishing.
@billmeek - I'm happy if you just reply and don't merge this PR - whatever seems best.

**Comment by billmeek** [comment]
Truth be told, I thought the HA MythTV project went away. Some time ago, I commented and
(I think) signed off www.home-assistant.io. If memory serves, the point was about error handling.
Now, using either RuntimeError or RuntimeWarning exceptions are the way to go. The
'MYTHTV_VERSION_LIST' still needs to be maintained. '32' is the last entry now. This may simply
go away in the future.

I searched for MythTV on www.home-assistant.io and got no matches.

1. It's OK with me if you want to put this on PyPI.
1. As above, re exceptions. if list(result.keys())[0] in ['Abort', 'Warning']: is still in HA-Component-mythtv-frontend
1. I'm sure you're referring to: https://github.com/MythTV/mythtv/tree/master/mythtv/bindings/python/MythTV/services_api

Take care.

**Comment by lindsaymarkward** [comment]
Thanks @billmeek.
The HA platform for MythTV has been happily working for multiple people, but never submitted to the main Home Assistant project. That's what I'm planning to do soon, after publishing this on PyPI (watch this space). 
I note there are changes but no version number bump since 0.1.9. I'll keep an eye out for commits to the code in your point 3.

For 2. Are you saying that we should remove that if statement checking the result because the API doesn't return a result with those values - but rather raises a RuntimeError or RuntimeWarning exception instead?

**Comment by billmeek** [comment]
On 6/12/20 4:40 PM, Lindsay Ward wrote:
> Thanks @billmeek <https://github.com/billmeek>.
> The HA platform for MythTV has been happily working for multiple people, but never submitted to the main Home Assistant project. That's what I'm 
> planning to do soon, after publishing this on PyPI (watch this space).
> I note there are changes but no version number bump since 0.1.9. I'll keep an eye out for commits to the code in your point 3.

You're right. Still 0.1.9 in the MythTV source. Shame on me.

> For 2. Are you saying that we should remove that if statement checking the result because the API doesn't return a result with those values - 
> but rather raises a RuntimeError or RuntimeWarning exception instead?

Exactly.

-- 
Bill

**Comment by lindsaymarkward** [comment]
Thanks @billmeek 
`warning: Check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too`
Are you happy for your email to be supplied for the PyPI package? (I have a gmail address for you)

**Comment by billmeek** [comment]
On 6/12/20 11:09 PM, Lindsay Ward wrote:
> Thanks @billmeek <https://github.com/billmeek>
> |warning: Check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too|
> Are you happy for your email to be supplied for the PyPI package? (I have a gmail address for you)

Hey Lindsay,

Not ignoring this, just not sure what to do.

Wondering if the PyPI version could just be considered a fork
with the proper license and someone else's author/email.

-- 
Bill

**Comment by calmor15014** [comment]
Bill and Lindsay,

That may be the better option. If you look at the HA docs, they want as much of the "work" as possible done in the PyPI library to keep that into public domain for sharing with other projects, and keep the HA-specific code in the PR to them. It keeps what goes into HA simpler and less likely to breakage if the API is where all of the interface is done.

I take that to mean instead of calling Send with options for endpoints and parsing dicts, calling a function like "raise_volume" or "get_image" and the API would do all of the logic to manage that. If the endpoints ever change, it can be managed in one spot.

Zoneminder is a good example of this. It was all in the HA code including the `requests` calls, but they extracted things into a PyPI API interface.

That does take much more work though and a commitment from someone. I have zero experience putting projects into PyPI and I've not been the most reliable so far.. :/ so I'm not sure I'm the guy, but I've had some major life changes and may be able to make a commitment, with help to get it kicked off.

**Comment by lindsaymarkward** [comment]
Thanks guys.
Bill, I'm happy if that's the way you want it. At no point do I want it to look like trying to take credit for any of your work!
I'll publish the API on PyPI (https://test.pypi.org/project/mythtvservicesapi/ currently) with my details as "author" and the existing link to the code in the mythtv repo so anyone could see where it comes from.

Jim; I think we'll do this iteratively so get it going (first test https://github.com/calmor15014/HA-Component-mythtv-frontend/pull/46 please) and then we'll consider either adding to the services API package or creating an in-between package that wraps the API calls as you're suggesting. I'll submit a PR to Home Assistant, which will get the devs' advice as well.
Thanks.

**Comment by calmor15014** [comment]
I agree completely with the iterative process, as we can keep the API backwards compatible and slowly migrate things out of the HA code while getting more users testing the official component.

Before we go to the PR for Home Assistant, I'd like to get at least some of the backend code branch I'm working on merged into master.  Can go into more details over there.  In the meantime I'll test the latest.

Thanks again for everyone's effort!

**Pull request closed without merging**
